# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .Tutorial_Unity
        unityVersion:
          - 2019.2.11f1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Commit CS
        uses: EndBug/add-and-commit@v4
        with:
          message: "Add the very useful text file"
          add: "./CSharp/"
          cwd: "./pathToRepo/"
          force: true
